name: Create daily issue

on:
  schedule:
    - cron: '0 8 * * *' # Runs every day at 9AM UTC+1
  workflow_dispatch: # Allows manual trigger

jobs:
  create_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create issue
        uses: actions/github-script@v7
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const issue = {
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: "Daily issue",
              body: `Hello there! This is your daily workout:
              - [ ] 20 pushups
              - [ ] 40 squats
              - [ ] 40 hostages`,
              assignees: ['quicoto']
            };
            github.rest.issues.create(issue);