name: Create Workout

on:
  schedule:
    - cron: '30 7 * * 1-5' # Runs every day from Monday to Friday at 8:15AM CET
  workflow_dispatch: # Allows manual trigger

jobs:
  create_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create issue
        uses: actions/github-script@v7
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const date = new Date();
            const issue = {
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `Workout for ${date.toISOString().split('T')[0]}`,
              body: `Hello there! This is your workout menu:
              - [ ] 10 Pushups
              - [ ] 10 Pushups
              - [ ] 20 Hostages
              - [ ] 20 Hostages
              - [ ] 20 Calf raises
              - [ ] 20 Calf raises 
              - [ ] 20 Squats
              - [ ] 20 Squats`,
              assignees: ['quicoto']
            };
            github.rest.issues.create(issue);
